### ISSUE TITLE
Contact form does not send emails

### ISSUE THREAD

**Issue by hoosoohoo** [anseve/mod_anseve_contactform#1]
Hi ANSEVE Contact Form
Contact form does not send emails
other contact form like sp contact form and DJ-EasyContact work
thanks

**Comment by anseve** [comment]
Hi,
did you get any error messages?
Are your mail settings correct? The settings can be modified via the Joomla admin area -> System -> Global Configuration -> Server -> Mail settings.

**Comment by hoosoohoo** [comment]
Hi,
thanks for your response
![settings](https://cloud.githubusercontent.com/assets/14958771/10279983/32528a5c-6b6a-11e5-9846-8565b460d852.jpg)

and the message is
Message
Thank you for your message.

**Comment by anseve** [comment]
Hi,
i tried to reproduce the problem. Everything works on my server.
Did you checked your junk mail folder?

Can you use smtp instead of PHP Mail see this tutorial:
http://optimumtheme.com/blog/using-gmail-to-send-mails-in-joomla.html

For Yahoo use this settings:
- Yahoo! SMTP server address: smtp.mail.yahoo.com
- Yahoo! SMTP user name: your Yahoo! Mail account
- Yahoo! SMTP password: your Yahoo! Mail password
- Yahoo! SMTP port: 465

**Comment by hoosoohoo** [comment]
Hi,
thanks for your response
Tried these
![sss1](https://cloud.githubusercontent.com/assets/14958771/10308094/cb0fdc26-6c33-11e5-8830-df5543cde242.jpg)
and
![sss2](https://cloud.githubusercontent.com/assets/14958771/10308099/d5cee698-6c33-11e5-8a0b-4210e72f8513.jpg)

the message was
Notice
SMTP connect() failed.

Error
There has been an error. Please try again.

**Comment by anseve** [comment]
Hi
Is your SMTP Host (smtp.yahoo.com) correct? Or is it smtp.mail.yahoo.com

**Comment by hoosoohoo** [comment]
I wrote smtp.yahoo.com

**Comment by hoosoohoo** [comment]
as you see

**Comment by anseve** [comment]
hi
yes I saw it. Can you use smtp.mail.yahoo.com as your host
If it does not work try this
http://www.bitsonline.org/technology-blog-bits/42-joomla/102-joomla-mail-settings-yahoo-small-business

**Comment by hoosoohoo** [comment]
Thank you so much, it works when using smtp.mail.yahoo.com as a host
thank you so much

**Comment by anseve** [comment]
Glad I could help
